export const DESCARGAR_PRODUCTOS = 'DESCARGAR_PRODUCTOS'
export const DESCARGAR_PRODUCTOS_EXITO = 'DESCARGAR_PRODUCTOS_EXITO'
export const DESCARGAR_PRODUCTOS_ERROR = 'DESCARGAR_PRODUCTOS_ERROR'

export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'

