//solo describen lo que esta pasando en la aplicacion
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS'
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO'
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR'

export const AGREGAR_USUARIO = 'AGREGAR_USUARIO'
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO'
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR'

export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const OBTENER_USUARIO_EXITO = 'OBTENER_USUARIO_EXITO'
export const OBTENER_USUARIO_ERROR = 'OBTENER_USUARIO_ERROR'


